//! Emit canonical `CREATE …` DDL text from an `Entity`/`TableDef`. The inverse of
//! the parser; used by the reverse-engineer engine. Output is intended to be
//! re-parseable (round-trip stable).

use crate::entity::Entity;

/// Quote a SQL identifier.
fn q(ident: &str) -> String {
    format!("\"{ident}\"")
}

/// Bare (unqualified) name from a possibly-qualified entity name (`schema.name` → `name`).
fn bare(name: &str) -> &str {
    name.rsplit('.').next().unwrap_or(name)
}

/// Whether a column type is one of the Postgres `serial` pseudo-types.
fn is_serial_type(ty: &str) -> bool {
    matches!(
        ty.trim().to_ascii_lowercase().as_str(),
        "serial" | "bigserial" | "smallserial" | "serial2" | "serial4" | "serial8"
    )
}

/// `CREATE TYPE "schema"."name" AS ENUM ('a', 'b');`
pub fn emit_enum(entity: &Entity) -> String {
    let schema = entity.schema.as_deref().unwrap_or("public");
    let name = bare(&entity.name);
    let values = entity
        .enum_values
        .iter()
        .map(|v| format!("'{}'", v.name.replace('\'', "''")))
        .collect::<Vec<_>>()
        .join(", ");
    format!("CREATE TYPE {}.{} AS ENUM ({});", q(schema), q(name), values)
}

/// `CREATE TABLE "schema"."name" ( … );` + `CREATE INDEX …;` + `COMMENT ON …;`
///
/// # Serial / identity columns
///
/// A column whose `data_type` is a serial variant (`serial`/`bigserial`/
/// `smallserial`) is emitted as just `"name" <serial>` — the `NOT NULL` and
/// `DEFAULT nextval(...)` that serial implies are dropped (Postgres adds them and
/// re-creates the owned sequence on apply). A column carrying `identity` is
/// emitted as `"name" <type> GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY` with
/// any default dropped (identity columns are implicitly `NOT NULL`).
///
/// # What is intentionally NOT re-emitted
///
/// Column-only `is_pk`/`is_unique` and `inline_fk` are not re-emitted: the Postgres
/// introspector decomposes these into table-level constraints, so re-emitting them
/// here would produce duplicate DDL.
pub fn emit_table(entity: &Entity) -> String {
    let schema = entity.schema.as_deref().unwrap_or("public");
    let name = bare(&entity.name);
    let qname = format!("{}.{}", q(schema), q(name));
    let Some(def) = &entity.table_def else {
        return format!("CREATE TABLE {qname} ();");
    };

    let mut lines: Vec<String> = Vec::new();

    // Columns
    for c in &def.columns {
        lines.push(emit_column_line(c));
    }

    // Table-level constraints
    for con in &def.constraints {
        lines.push(emit_table_constraint_line(con, schema));
    }

    let body = if lines.is_empty() {
        String::new()
    } else {
        format!("\n{}\n", lines.join(",\n"))
    };
    let mut out = format!("CREATE TABLE {qname} ({body});");

    // Indexes — every entry in def.indexes is emitted as-is. Filtering of
    // implicit PK/UNIQUE-backing indexes happens upstream in the introspector,
    // not here.
    for ix in &def.indexes {
        out.push('\n');
        out.push_str(&emit_index_sql(ix, &qname, name));
    }

    // Comments
    if let Some(tc) = &def.comments.table {
        out.push_str(&format!("\nCOMMENT ON TABLE {qname} IS '{}';", esc(tc)));
    }
    for c in &def.columns {
        if let Some(cm) = &c.comment {
            out.push_str(&format!(
                "\nCOMMENT ON COLUMN {qname}.{} IS '{}';",
                q(&c.name),
                esc(cm)
            ));
        }
    }
    out
}

/// Render one column definition line (indented, no trailing comma).
fn emit_column_line(c: &crate::entity::ColumnDef) -> String {
    // Serial columns are sugar (int + owned sequence). Emit just the serial
    // type — the implied NOT NULL and DEFAULT nextval(...) are re-created by
    // Postgres on apply, so re-emitting them would be redundant/wrong.
    if is_serial_type(&c.data_type) {
        return format!("  {} {}", q(&c.name), c.data_type);
    }

    let mut col = format!("  {} {}", q(&c.name), c.data_type);

    // Identity columns are implicitly NOT NULL and carry no default — emit the
    // GENERATED … AS IDENTITY clause and skip the default.
    if let Some(kind) = c.identity {
        use crate::entity::IdentityKind;
        let clause = match kind {
            IdentityKind::Always => "GENERATED ALWAYS AS IDENTITY",
            IdentityKind::ByDefault => "GENERATED BY DEFAULT AS IDENTITY",
        };
        col.push_str(&format!(" {clause}"));
        return col;
    }

    if !c.nullable {
        col.push_str(" NOT NULL");
    }
    if let Some(d) = &c.default_value {
        col.push_str(&format!(" DEFAULT {d}"));
    }
    col
}

/// Render one table-level constraint line (indented, no trailing comma).
/// Foreign keys default to the table's own `schema` when no `ref_schema` is set.
fn emit_table_constraint_line(con: &crate::entity::TableConstraint, schema: &str) -> String {
    use crate::entity::TableConstraint;
    match con {
        TableConstraint::PrimaryKey { columns, .. } => {
            format!("  PRIMARY KEY ({})", quote_cols(columns))
        }
        TableConstraint::Unique { columns, .. } => {
            format!("  UNIQUE ({})", quote_cols(columns))
        }
        TableConstraint::ForeignKey(fk) => {
            let ref_schema = fk.ref_schema.as_deref().unwrap_or(schema);
            let mut s = format!(
                "  FOREIGN KEY ({}) REFERENCES {}.{} ({})",
                quote_cols(&fk.columns),
                q(ref_schema),
                q(&fk.ref_table),
                quote_cols(&fk.ref_columns),
            );
            if let Some(a) = fk.on_delete {
                s.push_str(&format!(" ON DELETE {}", fk_action_sql(a)));
            }
            if let Some(a) = fk.on_update {
                s.push_str(&format!(" ON UPDATE {}", fk_action_sql(a)));
            }
            s
        }
        TableConstraint::Check { expression, .. } => {
            format!("  CHECK ({expression})")
        }
    }
}

/// Render a `CREATE [UNIQUE] INDEX … ON <qname> [USING method] (cols);` line.
/// `table_name` is the bare table name used to synthesize an index name when
/// the index has none.
fn emit_index_sql(ix: &crate::entity::IndexDef, qname: &str, table_name: &str) -> String {
    let cols = ix
        .columns
        .iter()
        .map(|c| match c.order {
            Some(crate::entity::SortOrder::Desc) => format!("{} DESC", q(&c.name)),
            _ => q(&c.name),
        })
        .collect::<Vec<_>>()
        .join(", ");
    let unique = if ix.unique { "UNIQUE " } else { "" };
    let idx_name = ix.name.clone().unwrap_or_else(|| format!("{table_name}_idx"));
    use crate::entity::IndexType;
    let using = match ix.index_type {
        Some(IndexType::Hash) => " USING hash",
        Some(IndexType::Gin) => " USING gin",
        Some(IndexType::Gist) => " USING gist",
        Some(IndexType::Brin) => " USING brin",
        Some(IndexType::SpGist) => " USING spgist",
        // btree (Some(Btree) or None) is the default — no USING clause.
        _ => "",
    };
    // Postgres grammar: CREATE [UNIQUE] INDEX name ON table [USING method] (cols)
    // — the access method goes AFTER the table, before the column list.
    format!("CREATE {unique}INDEX {} ON {qname}{using} ({cols});", q(&idx_name))
}

fn quote_cols(cols: &[String]) -> String {
    cols.iter().map(|c| q(c)).collect::<Vec<_>>().join(", ")
}

fn esc(s: &str) -> String {
    s.replace('\'', "''")
}

fn fk_action_sql(a: crate::entity::FkAction) -> &'static str {
    use crate::entity::FkAction;
    match a {
        FkAction::Cascade => "CASCADE",
        FkAction::Restrict => "RESTRICT",
        FkAction::SetNull => "SET NULL",
        FkAction::SetDefault => "SET DEFAULT",
        FkAction::NoAction => "NO ACTION",
    }
}

/// `CREATE SEQUENCE "schema"."name" …;`
///
/// The fully-rendered statement is carried verbatim in `entity.writes[0]` (set by
/// the introspector, which reconstructs it from `pg_sequences`/`pg_sequence`). We
/// emit that text, trimmed of any trailing whitespace/`;` and re-terminated with a
/// single `;`. Falls back to a bare `CREATE SEQUENCE "s"."n";` when no body was
/// captured.
pub fn emit_sequence(entity: &Entity) -> String {
    if let Some(body) = entity.writes.first() {
        let body = body.trim().trim_end_matches(';').trim_end();
        if !body.is_empty() {
            return format!("{body};");
        }
    }
    let schema = entity.schema.as_deref().unwrap_or("public");
    let name = bare(&entity.name);
    format!("CREATE SEQUENCE {}.{};", q(schema), q(name))
}

/// `CREATE VIEW "schema"."name" AS <definition>;`
/// The view body is carried in `entity.writes[0]` (set by the introspector).
pub fn emit_view(entity: &Entity) -> String {
    let schema = entity.schema.as_deref().unwrap_or("public");
    let name = bare(&entity.name);
    let body = entity.writes.first().map(String::as_str).unwrap_or("SELECT 1");
    let body = body.trim().trim_end_matches(';');
    format!("CREATE VIEW {}.{} AS {body};", q(schema), q(name))
}

/// `CREATE MATERIALIZED VIEW "schema"."name" AS <definition> WITH DATA;`
/// Body is carried in `entity.writes[0]` (same contract as `emit_view`); the
/// parser stores it without a `WITH DATA` clause, which we re-add here.
/// Trailing index statements (if any) are appended from `entity.table_def`,
/// rendered via the same `emit_index_sql` helper `emit_table` uses.
pub fn emit_matview(entity: &Entity) -> String {
    let schema = entity.schema.as_deref().unwrap_or("public");
    let name = bare(&entity.name);
    let qname = format!("{}.{}", q(schema), q(name));
    let body = entity.writes.first().map(String::as_str).unwrap_or("SELECT 1");
    let body = body.trim().trim_end_matches(';');
    let mut out = format!("CREATE MATERIALIZED VIEW {qname} AS {body} WITH DATA;");

    if let Some(def) = &entity.table_def {
        for ix in &def.indexes {
            out.push('\n');
            out.push_str(&emit_index_sql(ix, &qname, name));
        }
    }
    out
}

/// `CREATE OR REPLACE FUNCTION|PROCEDURE …;` for each overload, joined by a
/// blank line.
///
/// The bodies are carried verbatim in `entity.writes` (one per overload, set by
/// the introspector via `pg_get_functiondef`, whose output omits the trailing
/// semicolon). Each piece is trimmed of trailing whitespace and any trailing
/// `;`, then terminated with exactly one `;`, so the result is a valid script.
pub fn emit_routine(entity: &Entity) -> String {
    entity
        .writes
        .iter()
        .map(|w| {
            let body = w.trim_end();
            let body = body.trim_end_matches(';').trim_end();
            format!("{body};")
        })
        .collect::<Vec<_>>()
        .join("\n\n")
}

/// Emit DDL text for any reverse-engineerable entity, or `None` for kinds we
/// don't generate (External, Import/Export).
pub fn emit_entity(entity: &Entity) -> Option<String> {
    use crate::entity::EntityType;
    // Verbatim path: a source that already holds the exact `CREATE …` text (e.g.
    // SQLite's `sqlite_master.sql`) sets `raw_ddl` and bypasses the structured
    // emitter entirely. Re-terminate with a single trailing `;`.
    if let Some(raw) = &entity.raw_ddl {
        let body = raw.trim_end().trim_end_matches(';').trim_end();
        return Some(format!("{body};"));
    }
    match entity.entity_type {
        EntityType::Schema | EntityType::Extension | EntityType::Role => {
            crate::script::ddl_from_entity(entity)
        }
        EntityType::Sequence => Some(emit_sequence(entity)),
        EntityType::Enum => Some(emit_enum(entity)),
        EntityType::Table => Some(emit_table(entity)),
        EntityType::View => Some(emit_view(entity)),
        EntityType::MaterializedView => Some(emit_matview(entity)),
        EntityType::Function | EntityType::Procedure => Some(emit_routine(entity)),
        _ => None,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::entity::{EntityType, EnumValue};

    #[test]
    fn emits_enum() {
        let mut e = Entity::new(EntityType::Enum, "shop.order_status");
        e.enum_values = vec![
            EnumValue { name: "pending".into(), note: None },
            EnumValue { name: "paid".into(), note: None },
        ];
        assert_eq!(
            emit_enum(&e),
            "CREATE TYPE \"shop\".\"order_status\" AS ENUM ('pending', 'paid');"
        );
    }

    #[test]
    fn emits_table_roundtrips_through_parser() {
        use crate::entity::{ColumnDef, ForeignKey, IndexColumn, IndexDef, TableConstraint, TableDef};

        let mut e = Entity::new(EntityType::Table, "shop.orders");
        e.table_def = Some(TableDef {
            columns: vec![
                ColumnDef {
                    name: "id".into(),
                    data_type: "uuid".into(),
                    nullable: false,
                    default_value: None,
                    is_pk: true,
                    is_unique: false,
                    identity: None,
                    comment: Some("Order PK".into()),
                    inline_fk: None,
                },
                ColumnDef {
                    name: "customer_id".into(),
                    data_type: "uuid".into(),
                    nullable: false,
                    default_value: None,
                    is_pk: false,
                    is_unique: false,
                    identity: None,
                    comment: None,
                    inline_fk: None,
                },
                ColumnDef {
                    name: "total_cents".into(),
                    data_type: "integer".into(),
                    nullable: false,
                    default_value: Some("0".into()),
                    is_pk: false,
                    is_unique: false,
                    identity: None,
                    comment: None,
                    inline_fk: None,
                },
            ],
            constraints: vec![
                TableConstraint::PrimaryKey { name: None, columns: vec!["id".into()] },
                TableConstraint::ForeignKey(ForeignKey {
                    name: None,
                    columns: vec!["customer_id".into()],
                    ref_schema: Some("shop".into()),
                    ref_table: "customers".into(),
                    ref_columns: vec!["id".into()],
                    on_delete: None,
                    on_update: None,
                }),
            ],
            indexes: vec![IndexDef {
                name: Some("orders_customer_id_idx".into()),
                columns: vec![IndexColumn { name: "customer_id".into(), order: None }],
                unique: false,
                index_type: None,
            }],
            comments: Default::default(),
        });

        let sql = emit_table(&e);

        // Sanity on the emitted text:
        assert!(sql.contains("CREATE TABLE \"shop\".\"orders\""));
        assert!(sql.contains("\"id\" uuid NOT NULL"));
        assert!(sql.contains("\"total_cents\" integer NOT NULL DEFAULT 0"));
        assert!(sql.contains("PRIMARY KEY (\"id\")"));
        assert!(sql.contains("FOREIGN KEY (\"customer_id\") REFERENCES \"shop\".\"customers\" (\"id\")"));
        assert!(sql.contains("CREATE INDEX \"orders_customer_id_idx\" ON \"shop\".\"orders\" (\"customer_id\");"));
        assert!(sql.contains("COMMENT ON COLUMN \"shop\".\"orders\".\"id\" IS 'Order PK';"));

        // Round-trip: emitted DDL re-parses to a TableDef with the same structure.
        // Use the public parse_entity entry point with a fake table file path.
        let fake_path = std::path::Path::new("ddl/table/shop/orders.sql");
        let parsed_entity = crate::parser::parse_entity(fake_path, &sql)
            .expect("emitted table DDL should parse");
        let parsed = parsed_entity.table_def.expect("parsed entity should have a table_def");

        // Columns survive the round trip.
        let cols: Vec<&str> = parsed.columns.iter().map(|c| c.name.as_str()).collect();
        assert_eq!(cols, vec!["id", "customer_id", "total_cents"]);

        // Primary key survives the round trip.
        // Note: sqlparser preserves double-quoting from the emitted DDL in
        // column name strings (e.g. `"id"` not `id`); the constraint itself
        // does survive — we assert its presence and column count.
        let pk = parsed.constraints.iter().find_map(|c| match c {
            crate::entity::TableConstraint::PrimaryKey { columns, .. } => Some(columns),
            _ => None,
        });
        let pk_cols = pk.expect("PrimaryKey constraint must survive the round trip");
        assert_eq!(pk_cols.len(), 1, "PK must have exactly one column");
        assert!(
            pk_cols[0].contains("id"),
            "PK column must reference 'id', got: {:?}",
            pk_cols[0]
        );

        // Foreign key survives the round trip (references shop.customers).
        let fk = parsed.constraints.iter().find_map(|c| match c {
            crate::entity::TableConstraint::ForeignKey(fk) => Some(fk),
            _ => None,
        });
        let fk = fk.expect("ForeignKey constraint must survive the round trip");
        assert_eq!(fk.ref_table, "customers");
        assert_eq!(fk.ref_schema.as_deref(), Some("shop"));

        // Index name survives the round trip.
        let idx = parsed.indexes.iter().find(|i| {
            i.name.as_deref() == Some("orders_customer_id_idx")
        });
        assert!(
            idx.is_some(),
            "index 'orders_customer_id_idx' must survive the round trip"
        );
    }

    #[test]
    fn emits_view() {
        let mut e = Entity::new(EntityType::View, "shop.active_orders");
        e.references = vec![];
        // We store the view body in entity.writes[0] per the introspector contract:
        e.writes = vec!["SELECT * FROM shop.orders WHERE status = 'paid'".into()];
        let sql = emit_view(&e);
        assert_eq!(
            sql,
            "CREATE VIEW \"shop\".\"active_orders\" AS SELECT * FROM shop.orders WHERE status = 'paid';"
        );
    }

    #[test]
    fn emits_materialized_view() {
        let mut e = Entity::new(EntityType::MaterializedView, "analytics.daily_sales");
        e.writes = vec!["SELECT 1 AS x".to_string()];
        let sql = emit_matview(&e);
        assert_eq!(
            sql,
            "CREATE MATERIALIZED VIEW \"analytics\".\"daily_sales\" AS SELECT 1 AS x WITH DATA;"
        );
    }

    #[test]
    fn emit_entity_dispatches_matview() {
        let mut e = Entity::new(EntityType::MaterializedView, "analytics.daily_sales");
        e.writes = vec!["SELECT 1 AS x".to_string()];
        let sql = emit_entity(&e).expect("matview should emit");
        assert!(sql.starts_with("CREATE MATERIALIZED VIEW"));
    }

    #[test]
    fn emits_materialized_view_with_index() {
        use crate::entity::{IndexColumn, IndexDef, TableDef};

        let mut e = Entity::new(EntityType::MaterializedView, "analytics.daily_sales");
        e.writes = vec!["SELECT 1 AS x".to_string()];
        e.table_def = Some(TableDef {
            columns: vec![],
            constraints: vec![],
            indexes: vec![IndexDef {
                name: Some("daily_sales_x_idx".into()),
                columns: vec![IndexColumn { name: "x".into(), order: None }],
                unique: true,
                index_type: None,
            }],
            comments: Default::default(),
        });

        let sql = emit_matview(&e);
        assert!(
            sql.contains(
                "CREATE MATERIALIZED VIEW \"analytics\".\"daily_sales\" AS SELECT 1 AS x WITH DATA;"
            ),
            "got:\n{sql}"
        );
        assert!(
            sql.contains(
                "CREATE UNIQUE INDEX \"daily_sales_x_idx\" ON \"analytics\".\"daily_sales\" (\"x\");"
            ),
            "got:\n{sql}"
        );
    }

    #[test]
    fn emit_routine_joins_overloads() {
        // An overloaded function: two signatures captured as two `writes` bodies
        // (as the introspector would group them). `pg_get_functiondef` output has
        // no trailing semicolon — emit_routine must add exactly one per piece.
        let mut e = Entity::new(EntityType::Function, "app.f");
        e.schema = Some("app".into());
        e.writes = vec![
            "CREATE OR REPLACE FUNCTION app.f(a int) RETURNS int LANGUAGE sql AS $$ select 1 $$"
                .into(),
            "CREATE OR REPLACE FUNCTION app.f(a text) RETURNS int LANGUAGE sql AS $$ select 2 $$"
                .into(),
        ];
        let sql = emit_routine(&e);

        // Both overloads present.
        assert!(sql.contains("app.f(a int)"), "first overload missing:\n{sql}");
        assert!(sql.contains("app.f(a text)"), "second overload missing:\n{sql}");
        // Each statement ends in a single `;` (no double `;;`).
        assert!(sql.contains("$$ select 1 $$;"), "first body not ;-terminated:\n{sql}");
        assert!(sql.contains("$$ select 2 $$;"), "second body not ;-terminated:\n{sql}");
        assert!(!sql.contains(";;"), "no statement should be double-terminated:\n{sql}");
        // Separated by a blank line.
        assert!(sql.contains(";\n\n"), "overloads should be separated by a blank line:\n{sql}");

        // Dispatch wiring: emit_entity routes Function/Procedure to emit_routine.
        assert_eq!(emit_entity(&e).as_deref(), Some(sql.as_str()));
        let mut p = Entity::new(EntityType::Procedure, "app.p");
        p.writes = vec!["CREATE OR REPLACE PROCEDURE app.p() LANGUAGE sql AS $$ select 1 $$".into()];
        assert!(emit_entity(&p).unwrap().ends_with("$$;"));
    }

    #[test]
    fn emit_entity_dispatches_by_type() {
        let s = Entity::new(EntityType::Schema, "shop");
        assert_eq!(emit_entity(&s).unwrap(), "CREATE SCHEMA IF NOT EXISTS \"shop\";");
        let ext_none = Entity::new(EntityType::External, "auth.users");
        assert!(emit_entity(&ext_none).is_none());
    }

    #[test]
    fn emit_entity_uses_raw_ddl_verbatim() {
        // raw_ddl bypasses the structured emitter, single trailing `;`.
        let mut e = Entity::new(EntityType::Table, "t");
        e.raw_ddl = Some("CREATE TABLE t (a int)".into());
        assert_eq!(emit_entity(&e).unwrap(), "CREATE TABLE t (a int);");
        e.raw_ddl = Some("CREATE TABLE t (a int);\n".into()); // no double `;`
        assert_eq!(emit_entity(&e).unwrap(), "CREATE TABLE t (a int);");
        // Without raw_ddl, the structured emitter still runs.
        let plain = Entity::new(EntityType::Schema, "s");
        assert_eq!(emit_entity(&plain).unwrap(), "CREATE SCHEMA IF NOT EXISTS \"s\";");
    }

    #[test]
    fn emits_sequence_from_writes_body() {
        // The introspector stashes the fully-rendered statement in writes[0].
        let mut e = Entity::new(EntityType::Sequence, "app.counter");
        e.schema = Some("app".into());
        e.writes = vec![
            "CREATE SEQUENCE \"app\".\"counter\" AS bigint INCREMENT BY 1 \
             MINVALUE 1 MAXVALUE 9223372036854775807 START WITH 1 CACHE 1"
                .into(),
        ];
        let sql = emit_sequence(&e);
        assert!(sql.starts_with("CREATE SEQUENCE \"app\".\"counter\""), "got:\n{sql}");
        assert!(sql.contains("AS bigint"), "got:\n{sql}");
        assert!(sql.contains("INCREMENT BY 1"), "got:\n{sql}");
        assert!(sql.ends_with(';'), "must be ;-terminated:\n{sql}");
        assert!(!sql.contains(";;"), "no double-termination:\n{sql}");
        // Dispatch wiring.
        assert_eq!(emit_entity(&e).as_deref(), Some(sql.as_str()));
    }

    #[test]
    fn emits_sequence_fallback_without_body() {
        let mut e = Entity::new(EntityType::Sequence, "app.counter");
        e.schema = Some("app".into());
        assert_eq!(
            emit_sequence(&e),
            "CREATE SEQUENCE \"app\".\"counter\";"
        );
    }

    #[test]
    fn emit_table_serial_and_identity_columns() {
        use crate::entity::{ColumnDef, IdentityKind, TableConstraint, TableDef};

        let mut e = Entity::new(EntityType::Table, "app.thing");
        e.schema = Some("app".into());
        e.table_def = Some(TableDef {
            columns: vec![
                // serial column: emit just `bigserial`, no NOT NULL/DEFAULT.
                ColumnDef {
                    name: "id".into(),
                    data_type: "bigserial".into(),
                    nullable: false,
                    default_value: Some("nextval('app.thing_id_seq'::regclass)".into()),
                    is_pk: false,
                    is_unique: false,
                    identity: None,
                    comment: None,
                    inline_fk: None,
                },
                // identity column (ALWAYS): emit GENERATED ALWAYS AS IDENTITY, no default.
                ColumnDef {
                    name: "n".into(),
                    data_type: "integer".into(),
                    nullable: false,
                    default_value: None,
                    is_pk: false,
                    is_unique: false,
                    identity: Some(IdentityKind::Always),
                    comment: None,
                    inline_fk: None,
                },
                // standalone-referencing column: keep its real type + nextval default.
                ColumnDef {
                    name: "c".into(),
                    data_type: "integer".into(),
                    nullable: true,
                    default_value: Some("nextval('app.counter'::regclass)".into()),
                    is_pk: false,
                    is_unique: false,
                    identity: None,
                    comment: None,
                    inline_fk: None,
                },
            ],
            constraints: vec![TableConstraint::PrimaryKey {
                name: None,
                columns: vec!["id".into()],
            }],
            indexes: vec![],
            comments: Default::default(),
        });

        let sql = emit_table(&e);
        // serial: bigserial with no NOT NULL / no DEFAULT nextval.
        assert!(sql.contains("\"id\" bigserial"), "got:\n{sql}");
        assert!(!sql.contains("\"id\" bigserial NOT NULL"), "serial must not re-emit NOT NULL:\n{sql}");
        assert!(!sql.contains("nextval('app.thing_id_seq"), "serial must drop its owned-seq default:\n{sql}");
        // identity: GENERATED ALWAYS AS IDENTITY, no default.
        assert!(sql.contains("\"n\" integer GENERATED ALWAYS AS IDENTITY"), "got:\n{sql}");
        // standalone-referencing column keeps its default.
        assert!(sql.contains("\"c\" integer DEFAULT nextval('app.counter'::regclass)"), "got:\n{sql}");
    }

    #[test]
    fn emit_table_identity_by_default() {
        use crate::entity::{ColumnDef, IdentityKind, TableDef};

        let mut e = Entity::new(EntityType::Table, "app.thing");
        e.schema = Some("app".into());
        e.table_def = Some(TableDef {
            columns: vec![ColumnDef {
                name: "n".into(),
                data_type: "integer".into(),
                nullable: false,
                default_value: None,
                is_pk: false,
                is_unique: false,
                identity: Some(IdentityKind::ByDefault),
                comment: None,
                inline_fk: None,
            }],
            constraints: vec![],
            indexes: vec![],
            comments: Default::default(),
        });
        let sql = emit_table(&e);
        assert!(sql.contains("\"n\" integer GENERATED BY DEFAULT AS IDENTITY"), "got:\n{sql}");
    }

    #[test]
    fn emit_table_renders_index_access_methods() {
        use crate::entity::{ColumnDef, IndexColumn, IndexDef, IndexType, TableDef};

        let col = |n: &str, ty: &str| ColumnDef {
            name: n.into(), data_type: ty.into(), nullable: true, default_value: None,
            is_pk: false, is_unique: false, identity: None, comment: None, inline_fk: None,
        };
        let idx = |name: &str, col: &str, ty: Option<IndexType>| IndexDef {
            name: Some(name.into()),
            columns: vec![IndexColumn { name: col.into(), order: None }],
            unique: false,
            index_type: ty,
        };
        let mut e = Entity::new(EntityType::Table, "app.docs");
        e.table_def = Some(TableDef {
            columns: vec![col("tags", "text[]"), col("body", "tsvector"), col("n", "integer")],
            constraints: vec![],
            indexes: vec![
                idx("docs_tags_idx", "tags", Some(IndexType::Gin)),
                idx("docs_body_idx", "body", Some(IndexType::Gist)),
                idx("docs_n_brin_idx", "n", Some(IndexType::Brin)),
                idx("docs_n_hash_idx", "n", Some(IndexType::Hash)),
                idx("docs_n_btree_idx", "n", None),
            ],
            comments: Default::default(),
        });

        let sql = emit_table(&e);
        // Non-btree methods are emitted faithfully — a GIN/GiST index on an array /
        // tsvector column would be invalid as a plain btree, so the access method
        // must survive reverse-engineering.
        assert!(sql.contains("CREATE INDEX \"docs_tags_idx\" ON \"app\".\"docs\" USING gin (\"tags\");"), "got:\n{sql}");
        assert!(sql.contains("CREATE INDEX \"docs_body_idx\" ON \"app\".\"docs\" USING gist (\"body\");"), "got:\n{sql}");
        assert!(sql.contains("CREATE INDEX \"docs_n_brin_idx\" ON \"app\".\"docs\" USING brin (\"n\");"), "got:\n{sql}");
        assert!(sql.contains("CREATE INDEX \"docs_n_hash_idx\" ON \"app\".\"docs\" USING hash (\"n\");"), "got:\n{sql}");
        // btree (None) emits no USING clause.
        assert!(sql.contains("CREATE INDEX \"docs_n_btree_idx\" ON \"app\".\"docs\" (\"n\");"), "got:\n{sql}");
    }
}
