use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::path::{Path, PathBuf};

/// All entity types supported by dbd.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum EntityType {
    Schema,
    Extension,
    Role,
    Sequence,
    Enum,
    Table,
    View,
    MaterializedView,
    Function,
    Procedure,
    External,
    Import,
}

/// Entity types that live under a schema (file path: ddl/<type>/<schema>/<name>.ddl)
pub const TYPES_WITH_SCHEMA: &[EntityType] = &[
    EntityType::Sequence,
    EntityType::Enum,
    EntityType::Table,
    EntityType::View,
    EntityType::MaterializedView,
    EntityType::Function,
    EntityType::Procedure,
];

/// Entity types without schema qualification (file path: ddl/<type>/<name>.ddl)
pub const TYPES_WITHOUT_SCHEMA: &[EntityType] = &[
    EntityType::Role,
    EntityType::Schema,
    EntityType::Extension,
];

impl EntityType {
    /// Parse a type string from a folder name.
    pub fn from_folder_name(name: &str) -> Option<Self> {
        match name {
            "table" | "tables" => Some(Self::Table),
            "view" | "views" => Some(Self::View),
            "materialized_view" | "materialized_views" | "matview" | "matviews" => {
                Some(Self::MaterializedView)
            }
            "function" | "functions" => Some(Self::Function),
            "procedure" | "procedures" => Some(Self::Procedure),
            "enum" | "enums" => Some(Self::Enum),
            "role" | "roles" => Some(Self::Role),
            "sequence" | "sequences" => Some(Self::Sequence),
            _ => None,
        }
    }

    /// Whether this type requires schema qualification.
    pub fn has_schema(&self) -> bool {
        TYPES_WITH_SCHEMA.contains(self)
    }

    /// Lowercase tag for display, e.g. `EntityType::Table` → `"table"`.
    pub fn tag(&self) -> String {
        format!("{self:?}").to_lowercase()
    }

    /// On-disk DDL folder name for this type (e.g. `materialized_view`).
    /// Differs from `tag()` only where the lowercased variant name is not a
    /// readable folder (currently just `MaterializedView`).
    pub fn folder_name(&self) -> String {
        match self {
            EntityType::MaterializedView => "materialized_view".to_string(),
            other => other.tag(),
        }
    }
}

/// A parsed reference to another entity.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Reference {
    pub name: String,
    pub ref_type: Option<String>,
}

/// Foreign key constraint with full detail.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ForeignKey {
    pub name: Option<String>,
    pub columns: Vec<String>,
    pub ref_schema: Option<String>,
    pub ref_table: String,
    pub ref_columns: Vec<String>,
    pub on_delete: Option<FkAction>,
    pub on_update: Option<FkAction>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum FkAction {
    Cascade,
    Restrict,
    SetNull,
    SetDefault,
    NoAction,
}

impl FkAction {
    /// DBML FK action keyword for this action (used in `delete:`/`update:` settings).
    pub fn as_dbml(&self) -> &'static str {
        match self {
            FkAction::Cascade => "cascade",
            FkAction::Restrict => "restrict",
            FkAction::SetNull => "set null",
            FkAction::SetDefault => "set default",
            FkAction::NoAction => "no action",
        }
    }

    /// Map a DBML FK action keyword to an [`FkAction`]. `no action` → `Some(FkAction::NoAction)`
    /// (matches the exporter, which emits the keyword; the round-trip keeps `NoAction`
    /// distinguishable from "no FK action specified").
    pub fn from_dbml(s: &str) -> Option<Self> {
        match s.trim().to_ascii_lowercase().as_str() {
            "cascade" => Some(FkAction::Cascade),
            "restrict" => Some(FkAction::Restrict),
            "set null" => Some(FkAction::SetNull),
            "set default" => Some(FkAction::SetDefault),
            "no action" => Some(FkAction::NoAction),
            _ => None,
        }
    }
}

/// Table-level constraint.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type", rename_all = "snake_case")]
pub enum TableConstraint {
    PrimaryKey {
        name: Option<String>,
        columns: Vec<String>,
    },
    Unique {
        name: Option<String>,
        columns: Vec<String>,
    },
    ForeignKey(ForeignKey),
    Check {
        name: Option<String>,
        expression: String,
    },
}

/// How an identity column generates its value (`GENERATED … AS IDENTITY`).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum IdentityKind {
    /// `GENERATED ALWAYS AS IDENTITY` (`pg_attribute.attidentity = 'a'`).
    Always,
    /// `GENERATED BY DEFAULT AS IDENTITY` (`pg_attribute.attidentity = 'd'`).
    ByDefault,
}

/// Parsed column definition.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ColumnDef {
    pub name: String,
    pub data_type: String,
    pub nullable: bool,
    pub default_value: Option<String>,
    pub is_pk: bool,
    pub is_unique: bool,
    /// Identity generation, when the column is `GENERATED … AS IDENTITY`.
    /// `None` for non-identity columns. Replaces the former `is_identity: bool`.
    /// `#[serde(default)]` so snapshots written before this field existed (which
    /// carried `is_identity`) still deserialize — the obsolete field is ignored.
    #[serde(default)]
    pub identity: Option<IdentityKind>,
    pub comment: Option<String>,
    pub inline_fk: Option<ForeignKey>,
}

/// Index definition.
///
/// Models everything about a Postgres index that distinguishes it from another
/// index on the same columns, because reconcile compares an authored index
/// against an introspected one: anything this struct cannot hold is invisible to
/// that comparison and shows up as permanent, never-converging drift.
///
/// Every field past `index_type` is `#[serde(default)]` so snapshots written
/// before it existed still deserialize.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct IndexDef {
    pub name: Option<String>,
    pub columns: Vec<IndexColumn>,
    pub unique: bool,
    pub index_type: Option<IndexType>,
    /// `WHERE` predicate of a partial index, canonicalized via
    /// [`crate::sql_expr::canonicalize_predicate`] so the authored spelling and
    /// `pg_get_expr`'s analyzed one compare equal.
    #[serde(default)]
    pub predicate: Option<String>,
    /// Non-key payload columns: `INCLUDE (a, b)`.
    #[serde(default)]
    pub include: Vec<String>,
    /// `NULLS NOT DISTINCT` — makes NULLs collide instead of duplicate, so it
    /// changes what a UNIQUE index actually enforces.
    #[serde(default)]
    pub nulls_not_distinct: bool,
    /// Access-method storage parameters: `WITH (m = 16, ef_construction = 64)`.
    /// Keyed and ordered by name so an authored and a `reloptions` ordering
    /// compare equal.
    #[serde(default)]
    pub with_options: std::collections::BTreeMap<String, String>,
}

/// One entry in an index's key list: a column, or an expression over columns.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct IndexColumn {
    /// A column name, or the expression text when [`Self::is_expression`].
    pub name: String,
    /// Whether `name` holds an expression (`(context ->> 'module')`, `lower(x)`)
    /// rather than a column name. Emitters must not quote an expression as an
    /// identifier — that produces `column "(context ->> 'module')" does not exist`.
    #[serde(default)]
    pub is_expression: bool,
    pub order: Option<SortOrder>,
    /// `NULLS FIRST` (`Some(true)`) / `NULLS LAST` (`Some(false)`); `None` for
    /// the access method's default.
    #[serde(default)]
    pub nulls_first: Option<bool>,
    /// Operator class, e.g. `vector_cosine_ops` — picks which operators the
    /// index can answer, so two indexes differing only here are not the same.
    #[serde(default)]
    pub opclass: Option<String>,
}

/// An index access method. Postgres's set is open-ended (extensions add `hnsw`,
/// `ivfflat`, `bloom`, …), so unrecognized methods round-trip through
/// [`IndexType::Other`] rather than collapsing to the btree default.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum IndexType {
    Btree,
    Hash,
    Gin,
    Gist,
    Brin,
    /// SP-GiST. Serializes as `spgist` (Postgres's `pg_am.amname`).
    #[serde(rename = "spgist")]
    SpGist,
    /// Any other access method, held as its `pg_am.amname`.
    Other(String),
}

impl IndexType {
    /// The `pg_am.amname` for this access method — what `USING <method>` takes.
    pub fn amname(&self) -> &str {
        match self {
            IndexType::Btree => "btree",
            IndexType::Hash => "hash",
            IndexType::Gin => "gin",
            IndexType::Gist => "gist",
            IndexType::Brin => "brin",
            IndexType::SpGist => "spgist",
            IndexType::Other(name) => name,
        }
    }

    /// Parse a `pg_am.amname`, mapping the methods dbd names explicitly and
    /// keeping anything else verbatim.
    pub fn from_amname(amname: &str) -> Self {
        match amname.to_lowercase().as_str() {
            "btree" => IndexType::Btree,
            "hash" => IndexType::Hash,
            "gin" => IndexType::Gin,
            "gist" => IndexType::Gist,
            "brin" => IndexType::Brin,
            "spgist" => IndexType::SpGist,
            other => IndexType::Other(other.to_string()),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "lowercase")]
pub enum SortOrder {
    Asc,
    Desc,
}

/// Table and column comments.
#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct TableComments {
    pub table: Option<String>,
    pub columns: HashMap<String, String>,
}

/// Full parsed table structure.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TableDef {
    pub columns: Vec<ColumnDef>,
    pub constraints: Vec<TableConstraint>,
    pub indexes: Vec<IndexDef>,
    pub comments: TableComments,
}

/// Enum variant with optional note.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EnumValue {
    pub name: String,
    pub note: Option<String>,
}

/// The central data structure. All DDL objects flow through this type.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Entity {
    pub entity_type: EntityType,
    pub name: String,
    pub schema: Option<String>,
    pub file: Option<PathBuf>,
    pub format: Option<String>,
    pub refers: Vec<String>,
    pub references: Vec<Reference>,
    pub search_paths: Vec<String>,
    pub errors: Vec<String>,
    pub warnings: Vec<String>,
    pub reads: Vec<String>,
    pub writes: Vec<String>,
    pub table_def: Option<TableDef>,
    pub enum_values: Vec<EnumValue>,
    /// Verbatim DDL to emit as-is, bypassing the structured emitter. Used by sources
    /// that already hold the exact `CREATE …` text (e.g. SQLite's `sqlite_master.sql`).
    /// `None` for the Postgres/DBML paths, which reconstruct DDL from the structured model.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub raw_ddl: Option<String>,
}

impl Entity {
    /// Create a new empty entity with the given type and name.
    pub fn new(entity_type: EntityType, name: &str) -> Self {
        let (schema, _) = split_qualified_name(name);
        Self {
            entity_type,
            name: name.to_string(),
            schema,
            file: None,
            format: None,
            refers: Vec::new(),
            references: Vec::new(),
            search_paths: Vec::new(),
            errors: Vec::new(),
            warnings: Vec::new(),
            reads: Vec::new(),
            writes: Vec::new(),
            table_def: None,
            enum_values: Vec::new(),
            raw_ddl: None,
        }
    }

    /// Create an entity from a DDL file path.
    ///
    /// Path format: `ddl/<type>/<schema>/<name>.ddl` (schema-scoped)
    ///              `ddl/<type>/<name>.ddl` (non-schema types like role)
    pub fn from_file(path: &Path) -> Self {
        let parts: Vec<&str> = path.components()
            .filter_map(|c| c.as_os_str().to_str())
            .collect();

        // Find the "ddl" component and use everything after it.
        // This supports both relative paths ("ddl/table/...") and
        // absolute paths ("/path/to/fixtures/ddl/table/...").
        let ddl_pos = parts.iter().rposition(|&p| p == "ddl");
        let parts = match ddl_pos {
            Some(pos) => &parts[pos + 1..],
            None => &parts,
        };

        // An unrecognized folder name (typo, unsupported kind) is recorded as an
        // error on the entity rather than silently classified as a Table.
        let folder = parts.first().copied().unwrap_or("");
        let recognized_type = EntityType::from_folder_name(folder);
        let entity_type = recognized_type.unwrap_or(EntityType::Table);

        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("");

        let ext = path
            .extension()
            .and_then(|s| s.to_str())
            .unwrap_or("ddl");

        let (name, schema) = if entity_type.has_schema() && parts.len() >= 3 {
            let schema = parts[1].to_string();
            let qualified = format!("{}.{}", schema, stem);
            (qualified, Some(schema))
        } else {
            (stem.to_string(), None)
        };

        let mut entity = Self::new(entity_type, &name);
        entity.schema = schema;
        entity.file = Some(path.to_path_buf());
        entity.format = Some(ext.to_string());
        if recognized_type.is_none() {
            entity.errors.push(format!(
                "unrecognized DDL folder '{folder}' (expected table/view/materialized_view/function/procedure/enum/role/sequence)"
            ));
        }
        entity
    }

    /// Create a schema entity.
    pub fn schema(name: &str) -> Self {
        Self::new(EntityType::Schema, name)
    }

    /// Create an external entity (FK stub).
    pub fn external(name: &str) -> Self {
        Self::new(EntityType::External, name)
    }

    /// Create an import entity from a data file path.
    ///
    /// Path format: `import/<schema>/<name>.<ext>` or `import/<env>/<schema>/<name>.<ext>`
    /// Returns the entity with the file path set, format derived from extension.
    pub fn from_import_file(path: &Path) -> Self {
        let parts: Vec<&str> = path
            .components()
            .filter_map(|c| c.as_os_str().to_str())
            .collect();

        // Find "import" in the path and work from there
        let import_pos = parts.iter().rposition(|&p| p == "import");
        let after_import = match import_pos {
            Some(pos) => &parts[pos + 1..],
            None => &parts,
        };

        // Detect env prefix: import/dev/staging/file.csv → env=dev, schema=staging
        // vs import/staging/file.csv → env=None, schema=staging
        let (_env, schema_and_rest) = if after_import.len() >= 3
            && (after_import[0] == "dev" || after_import[0] == "prod")
        {
            (Some(after_import[0].to_string()), &after_import[1..])
        } else {
            (None, after_import)
        };

        let stem = path
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or("");

        let ext = path
            .extension()
            .and_then(|s| s.to_str())
            .unwrap_or("csv");

        let (name, schema) = if schema_and_rest.len() >= 2 {
            let schema = schema_and_rest[0].to_string();
            (format!("{schema}.{stem}"), Some(schema))
        } else {
            (stem.to_string(), None)
        };

        let mut entity = Self::new(EntityType::Import, &name);
        entity.schema = schema;
        entity.file = Some(path.to_path_buf());
        entity.format = Some(ext.to_string());
        entity
    }

    /// Whether this entity has validation errors.
    pub fn has_errors(&self) -> bool {
        !self.errors.is_empty()
    }
}

/// Split "schema.name" into (Some("schema"), "name"), or (None, "name").
pub fn split_qualified_name(name: &str) -> (Option<String>, String) {
    match name.split_once('.') {
        Some((schema, entity)) => (Some(schema.to_string()), entity.to_string()),
        None => (None, name.to_string()),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::Path;

    #[test]
    fn entity_type_from_folder_name() {
        assert_eq!(EntityType::from_folder_name("table"), Some(EntityType::Table));
        assert_eq!(EntityType::from_folder_name("view"), Some(EntityType::View));
        assert_eq!(EntityType::from_folder_name("function"), Some(EntityType::Function));
        assert_eq!(EntityType::from_folder_name("procedure"), Some(EntityType::Procedure));
        assert_eq!(EntityType::from_folder_name("enum"), Some(EntityType::Enum));
        assert_eq!(EntityType::from_folder_name("role"), Some(EntityType::Role));
        assert_eq!(EntityType::from_folder_name("sequence"), Some(EntityType::Sequence));
        assert_eq!(EntityType::from_folder_name("sequences"), Some(EntityType::Sequence));
        assert_eq!(EntityType::from_folder_name("unknown"), None);
    }

    #[test]
    fn entity_type_has_schema() {
        assert!(EntityType::Table.has_schema());
        assert!(EntityType::View.has_schema());
        assert!(EntityType::Enum.has_schema());
        assert!(EntityType::Sequence.has_schema());
        assert_eq!(EntityType::Sequence.tag(), "sequence");
        assert!(!EntityType::Role.has_schema());
        assert!(!EntityType::Schema.has_schema());
    }

    #[test]
    fn entity_from_table_file() {
        let entity = Entity::from_file(Path::new("ddl/table/config/lookups.ddl"));
        assert_eq!(entity.entity_type, EntityType::Table);
        assert_eq!(entity.name, "config.lookups");
        assert_eq!(entity.schema, Some("config".to_string()));
        assert_eq!(entity.file, Some(PathBuf::from("ddl/table/config/lookups.ddl")));
        assert_eq!(entity.format, Some("ddl".to_string()));
    }

    #[test]
    fn entity_from_view_file() {
        let entity = Entity::from_file(Path::new("ddl/view/config/genders.ddl"));
        assert_eq!(entity.entity_type, EntityType::View);
        assert_eq!(entity.name, "config.genders");
        assert_eq!(entity.schema, Some("config".to_string()));
    }

    #[test]
    fn entity_from_procedure_file() {
        let entity = Entity::from_file(Path::new("ddl/procedure/staging/import_lookups.ddl"));
        assert_eq!(entity.entity_type, EntityType::Procedure);
        assert_eq!(entity.name, "staging.import_lookups");
        assert_eq!(entity.schema, Some("staging".to_string()));
    }

    #[test]
    fn entity_from_enum_file() {
        let entity = Entity::from_file(Path::new("ddl/enum/config/status.sql"));
        assert_eq!(entity.entity_type, EntityType::Enum);
        assert_eq!(entity.name, "config.status");
        assert_eq!(entity.schema, Some("config".to_string()));
        assert_eq!(entity.format, Some("sql".to_string()));
    }

    #[test]
    fn entity_from_role_file() {
        let entity = Entity::from_file(Path::new("ddl/role/admin.ddl"));
        assert_eq!(entity.entity_type, EntityType::Role);
        assert_eq!(entity.name, "admin");
        assert_eq!(entity.schema, None);
    }

    #[test]
    fn entity_new_with_qualified_name() {
        let entity = Entity::new(EntityType::Table, "config.lookups");
        assert_eq!(entity.name, "config.lookups");
        assert_eq!(entity.schema, Some("config".to_string()));
    }

    #[test]
    fn entity_new_with_unqualified_name() {
        let entity = Entity::new(EntityType::Role, "admin");
        assert_eq!(entity.name, "admin");
        assert_eq!(entity.schema, None);
    }

    #[test]
    fn entity_schema_constructor() {
        let entity = Entity::schema("config");
        assert_eq!(entity.entity_type, EntityType::Schema);
        assert_eq!(entity.name, "config");
    }

    #[test]
    fn split_qualified_name_with_schema() {
        let (schema, name) = split_qualified_name("config.lookups");
        assert_eq!(schema, Some("config".to_string()));
        assert_eq!(name, "lookups");
    }

    #[test]
    fn split_qualified_name_without_schema() {
        let (schema, name) = split_qualified_name("admin");
        assert_eq!(schema, None);
        assert_eq!(name, "admin");
    }

    #[test]
    fn entity_has_errors() {
        let mut entity = Entity::new(EntityType::Table, "test");
        assert!(!entity.has_errors());
        entity.errors.push("missing file".to_string());
        assert!(entity.has_errors());
    }

    #[test]
    fn fk_action_serializes() {
        let fk = ForeignKey {
            on_delete: Some(FkAction::Cascade),
            on_update: Some(FkAction::NoAction),
            ..Default::default()
        };
        let json = serde_json::to_string(&fk).unwrap();
        assert!(json.contains("cascade"));
        assert!(json.contains("no_action"));
    }

    // ── EX1: External entity constructor ─────────────────

    #[test]
    fn ex1_external_entity_constructor() {
        let entity = Entity::external("pg_catalog.pg_type");
        assert_eq!(entity.entity_type, EntityType::External);
        assert_eq!(entity.name, "pg_catalog.pg_type");
        assert_eq!(entity.schema, Some("pg_catalog".to_string()));
    }

    // ── IF1: Import entity from CSV file ─────────────────

    #[test]
    fn if1_import_entity_from_csv_file() {
        let entity = Entity::from_import_file(Path::new("import/staging/lookups.csv"));
        assert_eq!(entity.entity_type, EntityType::Import);
        assert_eq!(entity.name, "staging.lookups");
        assert_eq!(entity.schema, Some("staging".to_string()));
        assert_eq!(entity.format, Some("csv".to_string()));
    }

    // ── IF2: Import entity from TSV file ─────────────────

    #[test]
    fn if2_import_entity_from_tsv_file() {
        let entity = Entity::from_import_file(Path::new("import/staging/data.tsv"));
        assert_eq!(entity.entity_type, EntityType::Import);
        assert_eq!(entity.name, "staging.data");
        assert_eq!(entity.format, Some("tsv".to_string()));
    }

    #[test]
    fn entity_type_from_folder_name_matview() {
        assert_eq!(EntityType::from_folder_name("materialized_view"), Some(EntityType::MaterializedView));
        assert_eq!(EntityType::from_folder_name("materialized_views"), Some(EntityType::MaterializedView));
        assert_eq!(EntityType::from_folder_name("matview"), Some(EntityType::MaterializedView));
        assert_eq!(EntityType::from_folder_name("matviews"), Some(EntityType::MaterializedView));
    }

    #[test]
    fn matview_has_schema_and_folder_name() {
        assert!(EntityType::MaterializedView.has_schema());
        assert_eq!(EntityType::MaterializedView.folder_name(), "materialized_view");
        assert_eq!(EntityType::Table.folder_name(), "table");
    }

    #[test]
    fn entity_from_matview_file() {
        let e = Entity::from_file(Path::new("ddl/materialized_view/analytics/daily_sales.ddl"));
        assert_eq!(e.entity_type, EntityType::MaterializedView);
        assert_eq!(e.name, "analytics.daily_sales");
        assert_eq!(e.schema, Some("analytics".to_string()));
    }
}
