use std::path::PathBuf;

/// A file to be generated by `dbd init`.
#[derive(Debug)]
pub struct InitFile {
    pub path: PathBuf,
    pub content: String,
}

/// Generate the list of files for a new dbd project.
///
/// Pure function — no I/O. Returns paths relative to the project root.
pub fn generate_init_files(name: &str, target: &str) -> Vec<InitFile> {
    let mut files = Vec::new();

    // design.yaml
    let design_yaml = match target {
        "supabase" => generate_supabase_config(name),
        _ => generate_postgres_config(name),
    };
    files.push(InitFile {
        path: PathBuf::from("design.yaml"),
        content: design_yaml,
    });

    // Directory structure (empty dirs represented by .gitkeep)
    let dirs = [
        "ddl/table",
        "ddl/view",
        "ddl/function",
        "ddl/procedure",
        "ddl/enum",
        "import",
    ];
    for dir in &dirs {
        files.push(InitFile {
            path: PathBuf::from(dir).join(".gitkeep"),
            content: String::new(),
        });
    }

    // Sample table DDL
    files.push(InitFile {
        path: PathBuf::from("ddl/table/public/example.ddl"),
        content: generate_sample_table(),
    });

    // import_jsonb_to_table procedure — required for JSONL imports
    files.push(InitFile {
        path: PathBuf::from("ddl/procedure/staging/import_jsonb_to_table.ddl"),
        content: generate_import_jsonb_procedure(),
    });

    files
}

fn generate_postgres_config(name: &str) -> String {
    format!(
        r#"project:
  name: {name}

target:
  postgres:
    url: $DATABASE_URL

schemas:
  - public
"#
    )
}

fn generate_supabase_config(name: &str) -> String {
    format!(
        r#"project:
  name: {name}

target:
  supabase:
    url: $DATABASE_URL

schemas:
  - public
  - config

external:
  - name: auth.users
    note: Supabase auth users table
  - name: auth.uid
    note: Supabase auth function (returns current user ID)
  - name: storage.objects
    note: Supabase storage objects table
  - name: storage.buckets
    note: Supabase storage buckets table

ignore:
  - auth.*
  - storage.*
  - realtime.*
  - supabase_*.*
  - extensions.*
  - pgbouncer.*
  - pgsodium.*
  - vault.*
  - graphql_public.*
"#
    )
}

fn generate_import_jsonb_procedure() -> String {
    r#"-- import_jsonb_to_table: generic JSONL import helper used by `dbd import`
-- called automatically when an import file has format: jsonl
-- args: p_source_table — temp table holding raw jsonb rows (single column: data jsonb)
--       p_target_table — fully-qualified destination table (schema.name)
--
-- Uses pg_catalog to resolve real column types, including enums (USER-DEFINED),
-- so explicit per-column casting works for any table without a custom procedure.
-- Skips GENERATED ALWAYS AS IDENTITY and stored generated columns automatically.
create or replace procedure staging.import_jsonb_to_table(
    p_source_table text
  , p_target_table text
)
language plpgsql
as
$$
declare
  v_target_schema text := split_part(p_target_table, '.', 1);
  v_target_name   text := split_part(p_target_table, '.', 2);
  v_col_exprs     text;
  v_sql           text;
begin
  -- Build per-column cast expressions using pg_catalog so that enum types
  -- (reported as USER-DEFINED by information_schema) are resolved correctly.
  select string_agg(
    format(
      '(data->>%L)::%s'
    , a.attname
    , case
        when t.typtype = 'e'
          then quote_ident(tn.nspname) || '.' || quote_ident(t.typname)
        else t.typname
      end
    )
  , ', ' order by a.attnum
  )
  into v_col_exprs
  from pg_catalog.pg_attribute  a
  join pg_catalog.pg_class       c  on c.oid  = a.attrelid
  join pg_catalog.pg_namespace   cn on cn.oid = c.relnamespace
  join pg_catalog.pg_type        t  on t.oid  = a.atttypid
  join pg_catalog.pg_namespace   tn on tn.oid = t.typnamespace
  where cn.nspname    = v_target_schema
    and c.relname     = v_target_name
    and a.attnum      > 0
    and not a.attisdropped
    and a.attidentity <> 'a'   -- exclude GENERATED ALWAYS AS IDENTITY
    and a.attgenerated = ''    -- exclude stored generated columns;

  if v_col_exprs is null then
    raise exception 'import_jsonb_to_table: table %.% not found or has no columns',
      v_target_schema, v_target_name;
  end if;

  v_sql := format(
    'insert into %s select %s from %I'
  , p_target_table
  , v_col_exprs
  , p_source_table
  );
  execute v_sql;
end;
$$
"#
    .to_string()
}

fn generate_sample_table() -> String {
    r#"-- example table — rename or delete this file
-- path convention: ddl/table/<schema>/<name>.ddl
create table if not exists example (
  id                       bigint generated always as identity primary key
, name                     text not null
, created_at               timestamptz not null default now()
);
"#
    .to_string()
}

/// Write init files to the project directory.
pub fn create_project(project_dir: &std::path::Path, name: &str, target: &str) -> crate::error::Result<Vec<InitFile>> {
    // Check if already initialized
    if project_dir.join("design.yaml").exists() {
        return Err(crate::error::DbdError::Config(
            "Project already initialized — design.yaml exists".to_string(),
        ));
    }

    let files = generate_init_files(name, target);

    for file in &files {
        let full_path = project_dir.join(&file.path);
        if let Some(parent) = full_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        std::fs::write(&full_path, &file.content)?;
    }

    Ok(files)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn generates_postgres_files() {
        let files = generate_init_files("myproject", "postgres");
        let paths: Vec<String> = files.iter().map(|f| f.path.display().to_string()).collect();

        assert!(paths.contains(&"design.yaml".to_string()));
        assert!(paths.contains(&"ddl/table/public/example.ddl".to_string()));
        assert!(paths.contains(&"ddl/procedure/staging/import_jsonb_to_table.ddl".to_string()));

        // design.yaml has correct content
        let config = files.iter().find(|f| f.path.display().to_string() == "design.yaml").unwrap();
        assert!(config.content.contains("name: myproject"));
        assert!(config.content.contains("postgres:"));
        assert!(config.content.contains("$DATABASE_URL"));
    }

    #[test]
    fn generates_supabase_files() {
        let files = generate_init_files("myproject", "supabase");
        let config = files.iter().find(|f| f.path.display().to_string() == "design.yaml").unwrap();
        assert!(config.content.contains("supabase:"));
        assert!(config.content.contains("auth.*"));
        assert!(config.content.contains("storage.*"));
        // Default external entities for Supabase
        assert!(config.content.contains("auth.users"), "should include auth.users external");
        assert!(config.content.contains("storage.objects"), "should include storage.objects external");
    }

    #[test]
    fn generates_directory_gitkeeps() {
        let files = generate_init_files("test", "postgres");
        let gitkeeps: Vec<&InitFile> = files.iter().filter(|f| f.path.ends_with(".gitkeep")).collect();
        assert_eq!(gitkeeps.len(), 6); // table, view, function, procedure, enum, import
    }

    #[test]
    fn sample_ddl_follows_convention() {
        let files = generate_init_files("test", "postgres");
        let ddl = files.iter().find(|f| f.path.display().to_string().contains("example.ddl")).unwrap();
        assert!(ddl.content.contains("create table if not exists"));
        assert!(ddl.content.contains("bigint generated always as identity"));
        assert!(ddl.content.contains(", name"));
        assert!(ddl.content.contains("default now()"));
    }

    #[test]
    fn scaffolds_import_jsonb_procedure() {
        let files = generate_init_files("test", "postgres");
        let proc = files
            .iter()
            .find(|f| f.path.display().to_string() == "ddl/procedure/staging/import_jsonb_to_table.ddl")
            .expect("import_jsonb_to_table.ddl should be scaffolded");
        assert!(proc.content.contains("import_jsonb_to_table"));
        assert!(proc.content.contains("p_source_table"));
        assert!(proc.content.contains("p_target_table"));
        // Uses pg_catalog for type resolution (handles enums correctly)
        assert!(proc.content.contains("pg_catalog.pg_attribute"));
        assert!(proc.content.contains("typtype = 'e'"));
        // Skips generated columns
        assert!(proc.content.contains("attidentity <> 'a'"));
        assert!(proc.content.contains("attgenerated = ''"));
    }

    #[test]
    fn create_project_writes_files() {
        let tmp = TempDir::new().unwrap();
        let files = create_project(tmp.path(), "test", "postgres").unwrap();
        assert!(tmp.path().join("design.yaml").exists());
        assert!(tmp.path().join("ddl/table/public/example.ddl").exists());
        assert!(tmp.path().join("ddl/view/.gitkeep").exists());
        assert!(tmp.path().join("ddl/procedure/staging/import_jsonb_to_table.ddl").exists());
        assert!(files.len() > 5);
    }

    #[test]
    fn create_project_fails_if_already_initialized() {
        let tmp = TempDir::new().unwrap();
        std::fs::write(tmp.path().join("design.yaml"), "existing").unwrap();
        let result = create_project(tmp.path(), "test", "postgres");
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("already initialized"));
    }

    #[test]
    fn default_project_name_from_dir() {
        // Just verify the function works with any name
        let files = generate_init_files("my-app", "postgres");
        let config = files.iter().find(|f| f.path.display().to_string() == "design.yaml").unwrap();
        assert!(config.content.contains("name: my-app"));
    }
}
