//! Is this directory a dbd project, and what is in it?
//!
//! The cheap counterpart to [`crate::Design::from_config`]. That reads the
//! config, scans the layout, parses every DDL file, resolves references and
//! sorts the dependency graph. This stops after the first two steps.
//!
//! The split exists for callers outside dbd — an indexer walking a repository
//! needs to decide *whether* a directory is worth parsing, and which parser to
//! use on it, before paying to parse anything. It is also the answer to "which
//! of these SQL files are actually source?", which is not obvious from the
//! outside: a dbd project contains generated SQL that looks exactly like
//! hand-written SQL.

use std::path::{Path, PathBuf};

use serde::Serialize;

use crate::config;
use crate::error::Result;
use crate::parser::ParserChoice;
use crate::scanner;

/// The config file that marks a directory as a dbd project.
const CONFIG_FILE: &str = "design.yaml";

/// Directories holding SQL dbd generated, which must never be read back as
/// source. `migrations/` accumulates one file per release and `snapshots/`
/// records the whole schema at a point in time, so a scanner that indexed
/// either would report every historical version of a table as a live entity.
const GENERATED_DIRS: &[&str] = &["migrations", "snapshots"];

/// dbd's own internal bookkeeping, of no interest to a caller.
const INTERNAL_DIRS: &[&str] = &[".dbd"];

/// Why a path is not in one of the file lists.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ExclusionReason {
    /// SQL dbd wrote — `migrations/`, `snapshots/`. Reading it back as source
    /// would resurrect superseded definitions.
    Generated,
    /// dbd's internal state directory.
    Internal,
    /// A file dbd used to scaffold into projects and now manages itself. It is
    /// dbd's plumbing rather than the project's schema.
    ManagedByDbd,
}

impl ExclusionReason {
    /// A short explanation, for a caller reporting what it skipped.
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::Generated => "generated by dbd — not a source definition",
            Self::Internal => "dbd internal state",
            Self::ManagedByDbd => "managed internally by dbd, not part of the project schema",
        }
    }
}

/// Something deliberately left out of the file lists, and why.
///
/// Carried rather than discarded, for the same reason [`scanner::ImportScan`]
/// carries its exclusions: "dbd found nothing" and "dbd skipped everything" are
/// different answers, and a bare empty list cannot tell them apart.
#[derive(Debug, Clone, Serialize)]
pub struct Exclusion {
    /// The excluded path — a directory for whole-tree exclusions, a file for
    /// individual ones. Absolute, under the surveyed directory.
    pub path: PathBuf,
    pub reason: ExclusionReason,
}

/// What a directory holds, read from its layout and config without parsing SQL.
#[derive(Debug, Clone, Serialize)]
pub struct ProjectSurvey {
    /// The surveyed directory.
    pub root: PathBuf,
    /// Its `design.yaml`.
    pub config_path: PathBuf,
    /// `project.name`.
    pub project: String,
    /// `project.version`, as written — `None` when the file omits it.
    ///
    /// Not defaulted here on purpose. The CLI itself disagrees about what a
    /// missing version means (`unwrap_or(1)` when reporting status,
    /// `unwrap_or(0)` when reverse-engineering), so a survey that picked one
    /// would be inventing a convention rather than describing the file.
    pub version: Option<u32>,
    /// `source.dialect`, verbatim — `postgresql` when unset.
    pub dialect: String,
    /// The parser [`dialect`](Self::dialect) and `source.parser` resolve to.
    ///
    /// Reported rather than left for the caller to derive, so nobody
    /// re-implements that mapping and disagrees with dbd about it. Pass it
    /// straight to [`crate::parser::parse_entity_with`].
    pub parser: ParserChoice,
    /// Schemas the project declares, in declaration order.
    pub schemas: Vec<String>,
    /// Entity definitions under `ddl/`, sorted. These are the files
    /// [`Self::parser`] reads.
    pub ddl_files: Vec<PathBuf>,
    /// RLS policy files under `policies/`, sorted.
    ///
    /// SQL, but not entity definitions — kept separate because parsing them as
    /// DDL would invent entities the project does not have.
    pub policy_files: Vec<PathBuf>,
    /// Seed data under `import/`, sorted. Data, not SQL.
    ///
    /// Every env's files, unfiltered: which ones load depends on the env a
    /// command runs with, and that is not a property of the directory. Use
    /// [`scanner::scan_import`] when the env matters.
    pub import_files: Vec<PathBuf>,
    /// Paths left out of the lists above, each with a reason. Empty when the
    /// project has none — nothing absent is reported.
    pub excluded: Vec<Exclusion>,
}

/// Survey `dir`, if it is a dbd project.
///
/// - `Ok(None)` — no `design.yaml`; this is an ordinary answer, not a failure.
///   A scanner meets far more non-projects than projects.
/// - `Err(_)` — a `design.yaml` that cannot be read, or that names a parser dbd
///   no longer has. Deliberately distinct from `Ok(None)`: collapsing the two
///   means a malformed project is silently skipped as "not dbd", and a caller
///   forced to tell them apart by matching error strings will get it wrong.
/// - `Ok(Some(_))` — a project, and what is in it.
///
/// No SQL is parsed. A file appearing in [`ProjectSurvey::ddl_files`] means it
/// is in the right place with the right extension, not that it is valid.
///
/// ```no_run
/// # fn example() -> dbd_core::Result<()> {
/// use std::path::Path;
///
/// if let Some(survey) = dbd_core::project::survey(Path::new("."))? {
///     for file in &survey.ddl_files {
///         let sql = std::fs::read_to_string(file)?;
///         let entity = dbd_core::parser::parse_entity_with(survey.parser, file, &sql)?;
///         println!("{:?} {}", entity.entity_type, entity.name);
///     }
/// }
/// # Ok(())
/// # }
/// ```
pub fn survey(path: &Path) -> Result<Option<ProjectSurvey>> {
    // Either the project directory or its config file. `dbd -c` accepts a
    // config under any name, so recognising only `design.yaml` here would make
    // a survey disagree with the CLI about what a project is.
    let (dir, config_path) = if path.is_dir() {
        (path.to_path_buf(), path.join(CONFIG_FILE))
    } else {
        let parent = path.parent().unwrap_or(Path::new(".")).to_path_buf();
        (parent, path.to_path_buf())
    };
    if !config_path.is_file() {
        return Ok(None);
    }
    let dir = dir.as_path();

    // Past this point every failure is an error, never `Ok(None)`: the
    // directory *is* a dbd project, it is just one dbd cannot read.
    let cfg = config::read(&config_path)?;
    let parser = ParserChoice::resolve(&cfg.source.dialect, cfg.source.parser.as_deref())?;

    let mut excluded = Vec::new();
    for name in GENERATED_DIRS {
        let path = dir.join(name);
        if path.is_dir() {
            excluded.push(Exclusion {
                path,
                reason: ExclusionReason::Generated,
            });
        }
    }
    for name in INTERNAL_DIRS {
        let path = dir.join(name);
        if path.is_dir() {
            excluded.push(Exclusion {
                path,
                reason: ExclusionReason::Internal,
            });
        }
    }

    // `scan_ddl` walks `ddl/` only, so `migrations/` and `snapshots/` are
    // already outside its reach — they are reported above for the caller's
    // benefit, not filtered here. What does need filtering is the handful of
    // files that live under `ddl/` but are dbd's rather than the project's.
    let mut ddl_files = Vec::new();
    for path in scanner::scan_ddl(dir)? {
        if crate::doctor::is_internally_managed(dir, &path) {
            excluded.push(Exclusion {
                path,
                reason: ExclusionReason::ManagedByDbd,
            });
        } else {
            ddl_files.push(path);
        }
    }

    let policy_files = scanner::scan_policies(dir)?;
    let mut import_files = scanner::scan_import(dir, None)?.files;
    import_files.sort();

    Ok(Some(ProjectSurvey {
        root: dir.to_path_buf(),
        config_path,
        project: cfg.project.name.clone(),
        version: cfg.project.version,
        dialect: cfg.source.dialect.clone(),
        parser,
        schemas: cfg.schema_names(),
        ddl_files,
        policy_files,
        import_files,
        excluded,
    }))
}

/// [`survey`] as JSON, self-describing in both outcomes.
///
/// `managed` is an explicit field rather than "an object, or null": a consumer
/// should never have to infer the answer from the absence of data, and a
/// non-project says *why* it is not one.
///
/// ```json
/// { "managed": true,  "project": "shop", "dialect": "postgresql",
///   "parser": "pg_query", "ddl_files": [ … ], "excluded": [ … ] }
///
/// { "managed": false, "root": "/some/dir", "reason": "no design.yaml" }
/// ```
///
/// `parser` is spelled as `source.parser` accepts it (`pg_query`, `verbatim`),
/// so the value round-trips back into a config.
///
/// An `Err` still means a project dbd could not read — that distinction is the
/// point of [`survey`] and is not flattened into the JSON.
pub fn survey_json(path: &Path) -> Result<serde_json::Value> {
    match survey(path)? {
        Some(s) => {
            let mut v = serde_json::to_value(&s)
                .map_err(|e| crate::error::DbdError::Config(format!("serialize survey: {e}")))?;
            if let Some(map) = v.as_object_mut() {
                map.insert("managed".to_string(), serde_json::Value::Bool(true));
            }
            Ok(v)
        }
        None => Ok(serde_json::json!({
            "managed": false,
            "root": path,
            "reason": format!("no {CONFIG_FILE}"),
        })),
    }
}
