// @generated by tests/doc_examples.rs — do not edit.
//
// Every Rust example in the embedder-facing docs, wrapped so it can be
// compiled. Cargo builds this as a test target, so an example that does
// not typecheck fails the build. See tests/doc_examples.rs for why.
//
// Regenerate: DBD_REGEN_DOC_EXAMPLES=1 cargo test --test doc_examples
//
// docs-digest: 0xe6ed7970427cb068
#![allow(dead_code, unused_imports, non_snake_case)]

// README.md — block 0
#[allow(unused, clippy::all)]
async fn doc_readme_md_0() -> dbd_core::Result<()> {
    #[allow(unused_variables)]
    let sql: &str = "";
    #[allow(unused_variables)]
    let database_url: &str = "";
    #[allow(unused_variables)]
    let path = std::path::Path::new("design.yaml");
    use dbd_core::Design;
    use dbd_core::adapter::postgres::PostgresAdapter;
    use dbd_core::design::Progress;
    use std::path::Path;

    async fn run_migrations(database_url: &str) -> anyhow::Result<()> {
        let design = Design::from_config(Path::new("database/design.yaml"), "prod")?;

        let adapter = PostgresAdapter::new(database_url, &design.config().project.name).await?;

        // apply(adapter, name, dry_run, scope, progress)
        let scope = design.resolve_scope(None, None)?;
        design
            .apply(&adapter, None, false, Some(&scope), Progress::none())
            .await?;
        Ok(())
    }
    Ok(())
}

// docs/skills/dbd/SKILL.md — block 0
#[allow(unused, clippy::all)]
async fn doc_docs_skills_dbd_skill_md_0() -> dbd_core::Result<()> {
    #[allow(unused_variables)]
    let sql: &str = "";
    #[allow(unused_variables)]
    let database_url: &str = "";
    #[allow(unused_variables)]
    let path = std::path::Path::new("design.yaml");
    use dbd_core::design::Progress;
    use dbd_core::{ApplyComplete, Design, connect};
    use std::path::Path;

    // 1. Load the declarative design for an environment (sync; scans ddl/ next to the config).
    let mut design = Design::from_config(Path::new("design.yaml"), "prod")?;

    // 2. Validate offline — no DB needed.
    let report = design.report(None, None);
    //    report.issues              → errors blocking the active scope (what apply refuses on)
    //    report.out_of_scope_issues → errored entities the scope excludes (non-blocking)
    //    report.warnings            → entities with warnings (e.g. unresolved entity refs)

    // 3. Connect an adapter — Postgres/SQLite/Convex chosen from the URL scheme.
    let adapter = connect("postgres://localhost/mydb", &design.config().project.name).await?;

    // 4. Apply schema + entities + pending migrations.
    //    The three callbacks travel together in ONE `Progress` value — they are not
    //    three arguments. `Progress::none()` for a silent run.
    let scope = design.resolve_scope(None, None)?; // None,None ⇒ full design, default deps policy
    design
        .apply(
            &*adapter,
            None,
            /*dry_run*/ false,
            Some(&scope),
            Progress {
                on_start: |desc: &str| println!("→ {desc}"),
                on_done: |desc: &str, err: Option<&str>| {
                    if let Some(e) = err {
                        eprintln!("✗ {desc}: {e}")
                    }
                },
                on_complete: |s: ApplyComplete| println!("applied {} entities", s.applied),
            },
        )
        .await?;

    // Or apply + import + policies in one call — the same pipeline `dbd deploy` runs:
    design
        .deploy(&*adapter, false, Some(&scope), |s| {
            println!("deployed to v{}", s.apply.to_version);
            println!("{} table(s) imported", s.import.tables);
            // Non-fatal diagnostics: skipped imports and failed policy files.
            for w in s.warnings() {
                eprintln!("warning: {w}");
            }
        })
        .await?;
    Ok(())
}

// docs/skills/dbd/SKILL.md — block 1
#[allow(unused, clippy::all)]
async fn doc_docs_skills_dbd_skill_md_1() -> dbd_core::Result<()> {
    #[allow(unused_variables)]
    let sql: &str = "";
    #[allow(unused_variables)]
    let database_url: &str = "";
    #[allow(unused_variables)]
    let path = std::path::Path::new("design.yaml");
    let parsed = dbd_core::parser::parse_sql(sql)?; // ParsedFile
    for e in &parsed.entities {
        // e.entity_type / e.schema / e.name  — read off the CREATE statement
        // e.refers, e.references             — typed edges (FK, view dep, function call)
        // e.reads, e.writes                  — separated, for functions and procedures
    }
    Ok(())
}

// docs/skills/dbd/SKILL.md — block 2
#[allow(unused, clippy::all)]
async fn doc_docs_skills_dbd_skill_md_2() -> dbd_core::Result<()> {
    #[allow(unused_variables)]
    let sql: &str = "";
    #[allow(unused_variables)]
    let database_url: &str = "";
    #[allow(unused_variables)]
    let path = std::path::Path::new("design.yaml");
    use dbd_core::parser::{Dialect, parse_sql_as};

    let parsed = parse_sql_as(Dialect::detect(sql), sql)?;
    println!("{:?} file, read as {:?}", parsed.kind, parsed.dialect);
    Ok(())
}

// src/assets/skills/dbd/SKILL.md — block 0
#[allow(unused, clippy::all)]
async fn doc_src_assets_skills_dbd_skill_md_0() -> dbd_core::Result<()> {
    #[allow(unused_variables)]
    let sql: &str = "";
    #[allow(unused_variables)]
    let database_url: &str = "";
    #[allow(unused_variables)]
    let path = std::path::Path::new("design.yaml");
    use dbd_core::design::Progress;
    use dbd_core::{ApplyComplete, Design, connect};
    use std::path::Path;

    // 1. Load the declarative design for an environment (sync; scans ddl/ next to the config).
    let mut design = Design::from_config(Path::new("design.yaml"), "prod")?;

    // 2. Validate offline — no DB needed.
    let report = design.report(None, None);
    //    report.issues              → errors blocking the active scope (what apply refuses on)
    //    report.out_of_scope_issues → errored entities the scope excludes (non-blocking)
    //    report.warnings            → entities with warnings (e.g. unresolved entity refs)

    // 3. Connect an adapter — Postgres/SQLite/Convex chosen from the URL scheme.
    let adapter = connect("postgres://localhost/mydb", &design.config().project.name).await?;

    // 4. Apply schema + entities + pending migrations.
    //    The three callbacks travel together in ONE `Progress` value — they are not
    //    three arguments. `Progress::none()` for a silent run.
    let scope = design.resolve_scope(None, None)?; // None,None ⇒ full design, default deps policy
    design
        .apply(
            &*adapter,
            None,
            /*dry_run*/ false,
            Some(&scope),
            Progress {
                on_start: |desc: &str| println!("→ {desc}"),
                on_done: |desc: &str, err: Option<&str>| {
                    if let Some(e) = err {
                        eprintln!("✗ {desc}: {e}")
                    }
                },
                on_complete: |s: ApplyComplete| println!("applied {} entities", s.applied),
            },
        )
        .await?;

    // Or apply + import + policies in one call — the same pipeline `dbd deploy` runs:
    design
        .deploy(&*adapter, false, Some(&scope), |s| {
            println!("deployed to v{}", s.apply.to_version);
            println!("{} table(s) imported", s.import.tables);
            // Non-fatal diagnostics: skipped imports and failed policy files.
            for w in s.warnings() {
                eprintln!("warning: {w}");
            }
        })
        .await?;
    Ok(())
}

// src/assets/skills/dbd/SKILL.md — block 1
#[allow(unused, clippy::all)]
async fn doc_src_assets_skills_dbd_skill_md_1() -> dbd_core::Result<()> {
    #[allow(unused_variables)]
    let sql: &str = "";
    #[allow(unused_variables)]
    let database_url: &str = "";
    #[allow(unused_variables)]
    let path = std::path::Path::new("design.yaml");
    let parsed = dbd_core::parser::parse_sql(sql)?; // ParsedFile
    for e in &parsed.entities {
        // e.entity_type / e.schema / e.name  — read off the CREATE statement
        // e.refers, e.references             — typed edges (FK, view dep, function call)
        // e.reads, e.writes                  — separated, for functions and procedures
    }
    Ok(())
}

// src/assets/skills/dbd/SKILL.md — block 2
#[allow(unused, clippy::all)]
async fn doc_src_assets_skills_dbd_skill_md_2() -> dbd_core::Result<()> {
    #[allow(unused_variables)]
    let sql: &str = "";
    #[allow(unused_variables)]
    let database_url: &str = "";
    #[allow(unused_variables)]
    let path = std::path::Path::new("design.yaml");
    use dbd_core::parser::{Dialect, parse_sql_as};

    let parsed = parse_sql_as(Dialect::detect(sql), sql)?;
    println!("{:?} file, read as {:?}", parsed.kind, parsed.dialect);
    Ok(())
}

// docs/llms/llms-full.txt — block 0
#[allow(unused, clippy::all)]
async fn doc_docs_llms_llms_full_txt_0() -> dbd_core::Result<()> {
    #[allow(unused_variables)]
    let sql: &str = "";
    #[allow(unused_variables)]
    let database_url: &str = "";
    #[allow(unused_variables)]
    let path = std::path::Path::new("design.yaml");
    use dbd_core::design::Progress;
    use dbd_core::{ApplyComplete, Design, connect};
    use std::path::Path;

    // Load the declarative design for an environment (sync; scans ddl/ next to the config).
    let mut design = Design::from_config(Path::new("design.yaml"), "prod")?;

    // Inspection — offline, no database. (`report` takes &mut self: it caches validation.)
    let report = design.report(None, None);
    // report.issues:              errors blocking the active scope (what apply refuses on)
    // report.out_of_scope_issues: errored entities the scope excludes (non-blocking)
    // report.warnings:            entities with warnings
    // report.gaps:                out-of-scope dependency gaps (when a scope is passed)

    // Connect an adapter — Postgres/SQLite/Convex is chosen from the URL scheme.
    let adapter = connect("postgres://localhost/mydb", &design.config().project.name).await?;

    // Resolve the scope once (None, None ⇒ full design, the scope's default deps policy).
    let scope = design.resolve_scope(None, None)?;

    // apply / import_data take FIVE arguments: (&*adapter, name, dry_run, scope,
    // progress). The three callbacks travel together in one `Progress` value —
    // on_start(&str), on_done(&str, Option<&str>), on_complete(summary) — they are
    // NOT three separate arguments. `Progress::none()` for a silent run.
    // deploy drops the name and takes on_complete directly: (&*adapter, dry_run,
    // scope, on_complete(DeployComplete)).
    design
        .apply(
            &*adapter,
            None,
            /*dry_run*/ false,
            Some(&scope),
            Progress {
                on_start: |desc: &str| println!("→ {desc}"),
                on_done: |desc: &str, err: Option<&str>| {
                    if let Some(e) = err {
                        eprintln!("✗ {desc}: {e}")
                    }
                },
                on_complete: |s: ApplyComplete| println!("applied {} entities", s.applied),
            },
        )
        .await?;
    design
        .import_data(&*adapter, None, false, Some(&scope), Progress::none())
        .await?;

    // Or apply + import + policies in one call — the same pipeline `dbd deploy`
    // runs, so an embedder and the CLI cannot drift. A failed policy file does not
    // fail the deploy; it lands in s.policies.failed and in s.warnings().
    design
        .deploy(&*adapter, false, Some(&scope), |s| {
            println!("v{} — {} table(s) imported", s.apply.to_version, s.import.tables);
            for w in s.warnings() {
                eprintln!("warning: {w}");
            }
        })
        .await?;
    // Use design.deploy_with_progress(&*adapter, dry_run, scope, Progress { .. })
    // for per-step callbacks (spinner / logging).

    // Dependency graph (for visualization) — returns Result.
    let graph = design.graph(None, None)?;
    // graph.nodes, graph.edges, graph.layers
    Ok(())
}
