//! `SchemaModel` v3 carries the project's history (#29).
//!
//! Additive, as v2 was: `history` is one more optional array, omitted when a
//! project has no snapshots, so a consumer that never heard of it reads a v3
//! payload exactly as it read v2. The version moves so that the next consumer
//! does not have to sniff for the field.

use dbd_core::Design;
use dbd_core::history;
use dbd_core::schema_model::{SchemaModel, build};
use serde_json::{Value, json};
use std::path::Path;

fn project(dir: &Path) -> Design {
    std::fs::write(
        dir.join("design.yaml"),
        "project:\n  name: m3\n\nsource:\n  dialect: postgresql\n  search_path: [app]\n\nschemas:\n  - app\n",
    )
    .unwrap();
    let t = dir.join("ddl/table/app");
    std::fs::create_dir_all(&t).unwrap();
    std::fs::write(
        t.join("people.ddl"),
        "set search_path to app;\ncreate table if not exists people (id integer primary key);",
    )
    .unwrap();
    Design::from_config_with_dir(&dir.join("design.yaml"), "dev", Some(dir)).unwrap()
}

fn snapshot(dir: &Path) {
    let snapshots = dir.join("snapshots");
    std::fs::create_dir_all(&snapshots).unwrap();
    let snap = json!({ "version": 1, "description": "v1", "timestamp": "2026-09-01T10:00:00Z",
        "tables": [{ "name": "people", "schema": "app", "indexes": [], "table_constraints": [],
            "columns": [{ "name": "id", "data_type": "integer", "nullable": false, "default_value": null,
                "is_pk": true, "is_unique": false, "comment": null, "inline_fk": null }] }],
        "enums": [] });
    std::fs::write(snapshots.join("001.json"), snap.to_string()).unwrap();
}

#[test]
fn the_model_is_version_3() {
    let tmp = tempfile::tempdir().unwrap();
    assert_eq!(build(&project(tmp.path()), None).unwrap().version, 3);
}

#[test]
fn a_model_without_history_omits_the_field() {
    let tmp = tempfile::tempdir().unwrap();
    let json = serde_json::to_value(build(&project(tmp.path()), None).unwrap()).unwrap();
    assert!(json.get("history").is_none(), "an empty history is absent, not []");
}

#[test]
fn a_model_carries_the_history_it_is_given() {
    let tmp = tempfile::tempdir().unwrap();
    let mut model = build(&project(tmp.path()), None).unwrap();
    snapshot(tmp.path());
    model.history = history::load(tmp.path()).unwrap();
    let json = serde_json::to_value(&model).unwrap();
    assert_eq!(json["history"][0]["baseline"], json!({ "tables": 1, "enums": 0 }));
}

#[test]
fn a_v2_payload_still_reads() {
    let tmp = tempfile::tempdir().unwrap();
    let mut v2: Value = serde_json::to_value(build(&project(tmp.path()), None).unwrap()).unwrap();
    v2["version"] = json!(2);
    let back: SchemaModel = serde_json::from_value(v2).unwrap();
    assert!(back.history.is_empty());
}

fn with_enum(dir: &Path) -> Design {
    let design = project(dir);
    drop(design);
    let e = dir.join("ddl/enum/app");
    std::fs::create_dir_all(&e).unwrap();
    std::fs::write(
        e.join("status.ddl"),
        "set search_path to app;\ncreate type status as enum ('active', 'paused', 'closed');\ncomment on type status is 'Account lifecycle.';",
    )
    .unwrap();
    Design::from_config_with_dir(&dir.join("design.yaml"), "dev", Some(dir)).unwrap()
}

/// The sidebar lists enums and their pages show their values (#34) — v3 carries them.
#[test]
fn the_model_carries_each_enum_with_its_values_in_order() {
    let tmp = tempfile::tempdir().unwrap();
    let json = serde_json::to_value(build(&with_enum(tmp.path()), None).unwrap()).unwrap();
    assert_eq!(
        json["enums"],
        json!([{ "schema": "app", "name": "status", "values": ["active", "paused", "closed"],
                 "note": "Account lifecycle.", "noteMd": "Account lifecycle." }])
    );
    assert_eq!(json["version"], 3, "additive within the unreleased v3");
}

#[test]
fn a_model_without_enums_omits_the_field() {
    let tmp = tempfile::tempdir().unwrap();
    let json = serde_json::to_value(build(&project(tmp.path()), None).unwrap()).unwrap();
    assert!(json.get("enums").is_none());
}

// ── What a table is, beyond its columns' names and types ───────────────────
//
// All additive and all omitted when absent, so a v3 consumer that never heard
// of them reads the same payload it did.

fn detailed(dir: &Path) -> Design {
    let design = project(dir);
    drop(design);
    std::fs::write(
        dir.join("ddl/table/app/orders.ddl"),
        "set search_path to app;\n\
         create table if not exists orders (\n  \
           id     bigint generated always as identity primary key\n, \
           ref_no bigint generated by default as identity\n, \
           qty    integer not null check (qty > 0)\n, \
           price  numeric not null\n, \
           total  numeric generated always as (qty * price) stored\n, \
           status text not null default 'open'\n, \
           constraint orders_price_ck check (price >= 0)\n\
         );\n\
         create index if not exists orders_open on orders (status) where status <> 'closed';\n\
         create index if not exists orders_qty on orders (qty);",
    )
    .unwrap();
    let s = dir.join("ddl/sequence/app");
    std::fs::create_dir_all(&s).unwrap();
    std::fs::write(
        s.join("invoice_no.ddl"),
        "set search_path to app;\n\
         create sequence if not exists invoice_no start with 1000;\n\
         comment on sequence invoice_no is 'Invoice numbers.';",
    )
    .unwrap();
    Design::from_config_with_dir(&dir.join("design.yaml"), "dev", Some(dir)).unwrap()
}

fn table_json(model: &Value, name: &str) -> Value {
    model["tables"]
        .as_array()
        .unwrap()
        .iter()
        .find(|t| t["name"] == name)
        .cloned()
        .unwrap_or_else(|| panic!("no table {name}"))
}

fn column_json(table: &Value, name: &str) -> Value {
    table["columns"]
        .as_array()
        .unwrap()
        .iter()
        .find(|c| c["name"] == name)
        .cloned()
        .unwrap_or_else(|| panic!("no column {name}"))
}

/// Inline and table-level CHECKs alike — the parser lifts an inline one onto the
/// table — inline first, as the parser orders them, each with its name if it has one.
#[test]
fn a_table_carries_its_check_constraints() {
    let tmp = tempfile::tempdir().unwrap();
    let m = serde_json::to_value(build(&detailed(tmp.path()), None).unwrap()).unwrap();
    assert_eq!(
        table_json(&m, "orders")["checks"],
        json!([{ "expression": "qty > 0" }, { "name": "orders_price_ck", "expression": "price >= 0" }])
    );
}

#[test]
fn a_partial_index_carries_its_predicate_and_a_full_one_does_not() {
    let tmp = tempfile::tempdir().unwrap();
    let m = serde_json::to_value(build(&detailed(tmp.path()), None).unwrap()).unwrap();
    let orders = table_json(&m, "orders");
    let index = |name: &str| {
        orders["indexes"]
            .as_array()
            .unwrap()
            .iter()
            .find(|i| i["name"] == name)
            .cloned()
            .unwrap()
    };
    assert_eq!(index("orders_open")["where"], json!("status <> 'closed'"));
    assert!(index("orders_qty").get("where").is_none());
}

#[test]
fn an_identity_column_says_how_it_generates_its_value() {
    let tmp = tempfile::tempdir().unwrap();
    let m = serde_json::to_value(build(&detailed(tmp.path()), None).unwrap()).unwrap();
    let orders = table_json(&m, "orders");
    assert_eq!(column_json(&orders, "id")["identity"], json!("always"));
    assert_eq!(column_json(&orders, "ref_no")["identity"], json!("by default"));
    assert!(column_json(&orders, "qty").get("identity").is_none());
}

/// The generation expression, and no default: Postgres keeps it where a DEFAULT
/// lives, but it is not one.
#[test]
fn a_generated_column_carries_its_expression_and_no_default() {
    let tmp = tempfile::tempdir().unwrap();
    let m = serde_json::to_value(build(&detailed(tmp.path()), None).unwrap()).unwrap();
    let total = column_json(&table_json(&m, "orders"), "total");
    assert_eq!(total["generated"], json!("qty * price"));
    assert!(total.get("def").is_none());
    assert!(
        column_json(&table_json(&m, "orders"), "status")
            .get("generated")
            .is_none()
    );
}

#[test]
fn a_sequence_is_an_entity_with_its_comment() {
    let tmp = tempfile::tempdir().unwrap();
    let m = serde_json::to_value(build(&detailed(tmp.path()), None).unwrap()).unwrap();
    let sequence = m["entities"]
        .as_array()
        .into_iter()
        .flatten()
        .find(|e| e["name"] == "invoice_no")
        .cloned();
    assert_eq!(
        sequence,
        Some(json!({ "schema": "app", "name": "invoice_no", "kind": "sequence",
                     "note": "Invoice numbers.", "noteMd": "Invoice numbers." }))
    );
}

#[test]
fn a_table_with_none_of_them_carries_none_of_the_fields() {
    let tmp = tempfile::tempdir().unwrap();
    let m = serde_json::to_value(build(&project(tmp.path()), None).unwrap()).unwrap();
    let people = table_json(&m, "people");
    assert!(people.get("checks").is_none());
    let id = column_json(&people, "id");
    assert!(id.get("identity").is_none() && id.get("generated").is_none());
}
